---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: geojson
  labels:
    app: geojson
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geojson
  template:
    metadata:
      labels:
        app: geojson
    spec:
      containers:
      - name: geojson
        image: geojson
        imagePullPolicy: Never

---
apiVersion: v1
kind: Service
metadata:
  name: geojson
spec:
  selector:
    app: geojson
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: geojson
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
 rules:
 - host: geojson.local
   http:
     paths:
     - path: /|/(.+)
       backend:
         serviceName: geojson
         servicePort: 8080
